### ISSUE TITLE
Deletes don't. 

### ISSUE THREAD

**Issue by kenrestivo-stem** [amperity/vault-clj#15] opened 2017-09-07 22:40 UTC
```clojure
(vault/delete-secret! @client  "/foo/bar/baz")
;; => true
```
```log4j
17-09-07 21:43:32 krestivo-x1carbon-1 DEBUG [vault.client.http:288] - Deleted secret /foo/bar/baz
```

```clojure
(vault/read-secret @client "/foo/bar/baz")
;;=> {:value "foo"}
```

Huh?

```sh

vault delete /foo/bar/baz
# => Success! Deleted '/foo/bar/baz' if it existed.
```

Works from the command line client. Weird

```clojure
(vault/read-secret @client "/foo/bar/baz")
;; => nil
```

```log4j
17-09-07 22:33:59 krestivo-x1carbon-1 ERROR [vault-utils.connectionspy:?] - 
                       clojure.core/eval                                           core.clj: 3194
                                     ...                                                         
     vault-utils.connectionspy/eval11539  abcfb28ff0b8969ad23059785823a5d74c1abd52-init.clj:    1
      vault-utils.connectionspy/spew-get                                  connectionspy.clj:   42
      vault-utils.connectionspy/spew-get                                  connectionspy.clj:   40
vault.client.http.HTTPClient/read-secret                                           http.clj:  423
vault.client.http.HTTPClient/read-secret                                           http.clj:  431
           vault.client.http/api-request                                           http.clj:   98
        vault.client.http/do-api-request                                           http.clj:   72
     vault.client.http/do-api-request/fn                                           http.clj:   73
    clj-http.client/wrap-unknown-host/fn                                         client.clj: 1009
            clj-http.links/wrap-links/fn                                          links.clj:   63
        clj-http.cookies/wrap-cookies/fn                                        cookies.clj:  131
          clj-http.client/wrap-method/fn                                         client.clj:  882
   clj-http.client/wrap-nested-params/fn                                         client.clj:  983
     clj-http.client/wrap-form-params/fn                                         client.clj:  948
    clj-http.client/wrap-content-type/fn                                         client.clj:  707
 clj-http.client/wrap-accept-encoding/fn                                         client.clj:  746
          clj-http.client/wrap-accept/fn                                         client.clj:  724
      clj-http.client/wrap-exceptions/fn                                         client.clj:  248
     clj-http.client/exceptions-response                                         client.clj:  239
           slingshot.support/stack-trace                                        support.clj:  201
clojure.lang.ExceptionInfo: clj-http: status 404
                     body: "{\"errors\":[]}\n"
                 chunked?: false
                  headers: {"Cache-Control" "no-store",
                            "Content-Type" "application/json",
                            "Date" "Thu, 07 Sep 2017 22:33:59 GMT",
                            "Content-Length" "14",
                            "Connection" "close"}
                   length: 14
    orig-content-encoding: nil
         protocol-version: {:name "HTTP", :major 1, :minor 1}
            reason-phrase: "Not Found"
              repeatable?: false
             request-time: 572
                   status: 404
               streaming?: true
          trace-redirects: ["https://vault:8200/v1/foo/bar/baz"]
                     type: :clj-http.client/unexceptional-status
clojure.lang.ExceptionInfo: Vault API errors: 
    errors: []
    status: 404
      type: :vault.client.http/api-error
```

What gives?

**Comment by greglook** [comment] 2017-09-08 05:55
The library should handle missing secrets better, so the 404 error could be improved. I believe what you're seeing is that Vault responds with a successful HTTP code when you delete a secret that doesn't exist, in order to avoid leaking information about whether a secret was present or not before the deletion. You should be able to delete secrets that actually exist (e.g. `secret/foo/bar`) and then see that they are no longer present.

**Comment by greglook** [comment] 2017-09-26 20:07
Actually it seems like the issue here is that deleting a secret doesn't revoke the internal lease on it. That should be easy to fix.

**Comment by greglook** [comment] 2017-09-26 20:15
I can't reproduce this behavior, so I think it's fixed in the current version of the code. I'll cut a new release with the LDAP auth and any other changes.

```clojure
user=> (vault/write-secret! client "secret/foo/bar/baz" {:value "foo"})
; 2017/09/26 13:13:01:566 PDT [DEBUG] http - Wrote secret secret/foo/bar/baz
true

user=> (vault/read-secret client "secret/foo/bar/baz" {:not-found ::missing})
; 2017/09/26 13:13:23:951 PDT [DEBUG] http - Read secret/foo/bar/baz (valid for 2764800 seconds)
{:value "foo"}

user=> (vault/delete-secret! client "secret/foo/bar/baz")
; 2017/09/26 13:13:43:504 PDT [DEBUG] http - Deleted secret secret/foo/bar/baz
true

user=> (vault/read-secret client "secret/foo/bar/baz" {:not-found ::missing})
:user/missing
```

**Closed by greglook** 2017-09-26 20:15 UTC
Labels: question
